### ISSUE TITLE
Method App\Http\Controllers\KeywordController::getArticles does not exist.

### ISSUE THREAD

**Issue by newbie2005** [alimranahmed/LaraBlog#124]
https://blog.xxx.net/keyword/article/ex

BadMethodCallException
Method App\Http\Controllers\KeywordController::getArticles does not exist.
https://blog.xxx.net/keyword/article/ex

When I check the app\Http\Controllers\KeywordController.php
No found getArticles

namespace App\Http\Controllers;

use App\Http\Requests\KeywordRequest;
use App\Models\Article;
use App\Models\Keyword;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class KeywordController extends Controller
{
    public function index()
    {
        $keywords = Keyword::with('articles')->get();
        return view('backend.keywords.index', compact('keywords'));
    }
}

**Comment by alimranahmed** [comment]
Hello @newbie2005 

Fixed this issue. You can pull the master branch to get the updated code. 

Thanks a lot for reporting.
