### ISSUE TITLE
enrollment not verified

### ISSUE THREAD

**Issue by tecinfotecnologia** [alimranahmed/LaraBlog#166]
I receive the email for confirmation, but when I click on confirm, it does not change the status on the dashboard, if you can help me, I will be grateful!

![image](https://github.com/alimranahmed/LaraBlog/assets/94642534/43dc2c15-4afa-4a9f-adeb-06bbbea24429)

link confirmation

https://site.dominio.com.br/subscription/confirm?token=JtxKjAqcokEnIWRm

![image](https://github.com/alimranahmed/LaraBlog/assets/94642534/5cb56f0a-72cd-44c8-a220-f50c0016f7fd)

**Comment by alimranahmed** [comment]
@tecinfotecnologia I just checked this feature when I clicked on the link in email it works without any issue. Did you got any error after click on that link? The functionality seems working correctly.
