### ISSUE TITLE
missing component

### ISSUE THREAD

**Issue by meghakundu** [alimranahmed/LaraBlog#177]
Please kindly help to find the missing component "frontend.subscribe" @alimranahmed

**Comment by alimranahmed** [comment]
I don't know why you are facing this issue. I can see `frontend.subscribe` component exists. Check here: https://github.com/alimranahmed/LaraBlog/blob/main/resources/views/livewire/frontend/subscribe.blade.php

**Comment by alimranahmed** [comment]
@meghakundu, I updated the main branch with latest laravel. Please pull the latest branch and feel free to run `composer update` in case you have a different setup then mine.

**Comment by meghakundu** [comment]
> @meghakundu, I updated the main branch with latest laravel. Please pull the latest branch and feel free to run `composer update` in case you have a different setup then mine.

"require(E:\xampp\htdocs\LaraBlog\vendor\composer/../../app/Helpers/helpers.php): Failed to open stream: No such file or directory in E:\xampp\htdocs\LaraBlog\vendor\composer\autoload_real.php" can please help to get through..

**Comment by alimranahmed** [comment]
Have you pulled the latest `main` branch and then executed `composer update`? 
Whe are you seeing this error?

**Comment by meghakundu** [comment]
Need to check again, haven't check since past few weeks.

**Comment by meghakundu** [comment]
> Have you pulled the latest `main` branch and then executed `composer update`? Whe are you seeing this error?

To reopen the web without login, had to do so:
![image](https://github.com/user-attachments/assets/349b918d-79e5-465e-ac3a-58d1e4457864)
Thereafter,
![image](https://github.com/user-attachments/assets/992d88b4-f767-4d95-a002-feeb3514402d)

**Comment by meghakundu** [comment]
Thanx working now!
