### ISSUE TITLE
Add new user, edit user, view user and so on....

### ISSUE THREAD

**Issue by eliyas5044** [alimranahmed/LaraBlog#21]
@alimranahmed bro, you have many problem in this repository, please check again in your machine. But i used xampp server, not homestead

**Comment by alimranahmed** [comment]
Ca you specify what many problems are you facing? I am using here in my local machine(no homestead). It would be great if you point out every problem your are facing. I will try hard to solve the issues. Thanks

**Comment by alimranahmed** [comment]
I have found some issues with roles while creating and updating user. Just fixed those issues. Please let me know if any issues left. Thanks

**Comment by eliyas5044** [comment]
yes bro, first i tried that field and got error. So i left and didn't try more. btw, it's good, you found problems :)
