### ISSUE TITLE
Upgrade to Laravel 5.8(Latest stable)

### ISSUE THREAD

**Issue by alimranahmed** [alimranahmed/LaraBlog#65]

**Comment by m-rufflesmcghie** [comment]
Hey
So this is as far as I have got 
Forked Repo and downloaded to local machine
Updated Laravel & Dependencies no issues found. 
Trying to update to Bootstrap 4, receiving npm issues think this is due to Homestead environment
Can you confirm where you run this project originally.

**Comment by alimranahmed** [comment]
I run this project in ubuntu server. As local environment I use valet in my mac. By the way I don't these these information are relevant with the issue of upgrading to bootstrap 4. 

Firstly, I think upgrading to Laravel 5.8 and upgrading all other php dependencies(in composer.json) is enough to complete this issue. Upgrading to bootstrap 4 is a different issue, we need to fix that in separately because this is highly related to frontend design and not related to backend(php). Just upgrading from bootstrap 3 to 4 will break a lot of things in view which is what require a separate issue.

**Comment by alimranahmed** [comment]
I have already created a different [issue](https://github.com/alimranahmed/LaraBlog/issues/58) for upgrading to bootstrap 4
